/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCallbackRouteImport } from './routes/api/callback'
import { Route as AuthedGenerateRouteImport } from './routes/_authed/generate'
import { Route as AuthedFavoritesRouteImport } from './routes/_authed/favorites'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallbackRoute = ApiCallbackRouteImport.update({
  id: '/api/callback',
  path: '/api/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedGenerateRoute = AuthedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFavoritesRoute = AuthedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AuthedAccountRoute
  '/favorites': typeof AuthedFavoritesRoute
  '/generate': typeof AuthedGenerateRoute
  '/api/callback': typeof ApiCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AuthedAccountRoute
  '/favorites': typeof AuthedFavoritesRoute
  '/generate': typeof AuthedGenerateRoute
  '/api/callback': typeof ApiCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/favorites': typeof AuthedFavoritesRoute
  '/_authed/generate': typeof AuthedGenerateRoute
  '/api/callback': typeof ApiCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/favorites' | '/generate' | '/api/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/favorites' | '/generate' | '/api/callback'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/account'
    | '/_authed/favorites'
    | '/_authed/generate'
    | '/api/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiCallbackRoute: typeof ApiCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/callback': {
      id: '/api/callback'
      path: '/api/callback'
      fullPath: '/api/callback'
      preLoaderRoute: typeof ApiCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/generate': {
      id: '/_authed/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthedGenerateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/favorites': {
      id: '/_authed/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthedFavoritesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedFavoritesRoute: typeof AuthedFavoritesRoute
  AuthedGenerateRoute: typeof AuthedGenerateRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedFavoritesRoute: AuthedFavoritesRoute,
  AuthedGenerateRoute: AuthedGenerateRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiCallbackRoute: ApiCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
